# Exercise 2.B cleaning up data

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('test_data.csv')
df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

Add a cell to show column statistics on df using the describe method

In [5]:
df.describe()

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

Filter the DataFrame to show only rows where Age is greater than 18

In [6]:
df_filter = df[(df['Age'] > 18)]
print(df_filter)

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

Filter the DataFrame to show only rows where Score is greater than 50 and less than
100.

In [ ]:
df_filter = df[(df['Score'] > 50) & (df['Score'] < 100)]
print(df_filter)
#has issues with the and had to change it to & 
#also had to reprint the df([]) for the & otherwise get error message

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

Create new variable df_cleaned. Assign it the value of df, using the drop function to remove rows where the Score is less than 0 (i.e., invalid score data). Then call df_cleaned to review the result

In [44]:
df_cleaned = pd.DataFrame(df)
df_cleaned = df.drop(df[df['Score'] < 0].index)
# had to use .index to ge the rows of the ones being dropped
df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

Continuing to work with df_cleaned for the rest of these steps, remove the City column from the DataFrame using drop. Call df_cleaned to review the result

In [45]:
df_cleaned = df.drop('City', axis=1) #axis1 columns, axis0 rows
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
2   3  Charlie  22.0   -1.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

Replace all missing Age values with the mean Age of the DataFrame using fillna. Call df_cleaned to review the result

In [46]:
df_cleaned = df_cleaned.fillna(25.0)
df_cleaned
#def.descibe result mean is 25.0

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.0   92.0
2   3  Charlie  22.0   -1.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0   25.0
6   7    Grace  25.0   55.0
7   8    Heidi  18.0   90.0

Replace any Score value of 0 with the mean Score of the DataFrame using replace. Call df_cleaned to review the result.

In [47]:
df_cleaned.replace({'Score': {0: 66.285714}}, inplace=True )
df_cleaned
#no change i have no score value of 0? only a -1?

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.0   92.0
2   3  Charlie  22.0   -1.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0   25.0
6   7    Grace  25.0   55.0
7   8    Heidi  18.0   90.0

Remove any remaining rows that contain NaN values using the dropna function. Call df_cleaned to review the result

In [48]:

df_cleaned = df_cleaned.dropna()
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.0   92.0
2   3  Charlie  22.0   -1.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0   25.0
6   7    Grace  25.0   55.0
7   8    Heidi  18.0   90.0

Apply the values from ID as index labels, then remove column ID. (Pay attention to the numbering!) Call df_cleaned to review the result.

In [51]:
df_cleaned = df.set_index('ID') #st.index removes the index and uses a column to label rows
df_cleaned

       Name   Age       City  Score
ID
1    Alicia  25.0         NY   85.0
2       Bob   NaN         LA   92.0
3   Charlie  22.0    Chicago   -1.0
4   Dominic  19.0    Houston   65.0
5       Eve  31.0    Phoenix   78.0
6     Frank  35.0     Boston    NaN
7     Grace   NaN     Austin   55.0
8     Heidi  18.0  San Diego   90.0